### ISSUE TITLE
Testing Overhaul

### ISSUE THREAD

**Issue by SimonBoothroyd** [SimonBoothroyd/nonbonded#2]
## Description
Currently the framework does not have any unit or integration tests. These will be added via several PR's over the next couple of days.

### Model Tests

  - [x] Validating the library models (#1).

### CRUD Tests

  - [x] Add tests for the project CRUD (#4).
  - [x] Add tests for the data set CRUD (#4).
  - [x] Add tests for the results CRUD (#4).

### REST API Tests

  - [x] Add tests for the `projects` endpoint and it's children (#5).
  - [x] Add tests for the `datasets` endpoint (#5).
  - [x] Add tests for the `molecules` endpoint (#5).

### Statistics
 
  - [x] Test the statistics module (#7).

### Utilities

  - [x] Test the re-indexing utilities (#8).
  - [x] Test the data frame re-ordering utility (#8).
  - [x] Test the checkmol function group assignment utility (#8).

### Curation

  - [X] Test the filtering components (#9)
  - [x] Test the ThermoML components (#9)
  - [x] Test the Selection components (#9)

### CLI

  - [X] Add tests for the core CLIs (#10).
  - [x] Add tests for the remaining CLIs.

### Input File Generation

  - [x] Creating input files from the Jinja templates.
  - [x] Create input files from the input generation factories.
